version: '3.8'

# Configuração para ambiente de staging
services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DefaultConnection=Server=db;Database=EnergiaDB_Staging;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    ports:
      - "5029:80"
    container_name: energia-api-staging

  db:
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
    container_name: energia-db-staging
    ports:
      - "1434:1433"
